on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Running Prettier
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GH_TOKEN: ${{ github.token }}
