on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Formatting
    steps:
      - name: Running Prettier
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
